name: pull full data

on:
  schedule:
    - chron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo content
      uses: actions/checkout@v3 # checkout the repository content

    - name: fetch data, write timestamp as filename
      run: |
          curl 'https://gbfs.citibikenyc.com/gbfs/en/station_information.json' -o data/temp_stations.json \
          curl 'https://gbfs.citibikenyc.com/gbfs/en/station_status.json' -o data/temp_status.json \
          
          timestamp=($jq -r '.last_updated' 'data/temp-status.json') \

          mv temp_stations.json "data/{$timestamp}_stations.json" \
          mv temp_status.json "data/{$timestamp}_status}.json" \

    - name: commit files
      run: |
      git config --local user.email "action@github.com"
      git config --local user.name "GitHub Action"
      git add -A
      git diff-index --quiet HEAD || (git commit -a -m "pulled data on schedule" --allow-empty)

    - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 